# @author DieFriiks / CustomCraftDev / undeaD_D
# @link www.pokemon-online.xyz
# @github https://github.com/CustomCraftDev/Gold2Xp
debug: nope

msg:
  nopermission: '&c[Gold2Xp] you dont have permission to that command'
  disable: '&c[Gold2Xp] was disabled'
  reset: '&c[Gold2Xp] was reset'
  reload: '&c[Gold2Xp] was reloaded'

event:
  block: 'GOLD_BLOCK'
  item: 'GOLD_INGOT'
  xp: 7

help:
  info:
    - 'Dont touch debug mode ...'
    - 'This help section can be deleted if you like ^^'
    - 'for block and item use bukkit Materials only'
    - 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'
    - 'all messages support bukkit colorcodes ...'
    - 'http://www.minecraftforum.net/forums/support/server-support/tutorials-and-faqs/1940467-bukkit-colour-codes'
    - 'if an update is available the plugin will not load itself, till it gets updated :P'
    - 'if you have any questions, feel free to ask me on bukkit.org or later even on my website (curently under construction)'
    - 'remember: have fun playing' 
  cmd:
    - '/g2x reload  <-- reloads the settings from config.yml'
    - '/g2x reset   <-- resets the config.yml to default and then basically calls /g2x reload'
    - '/g2x disable <-- disable Gold2Xp, till next reload/restart'
  permissions:
    - 'g2x.reload   <-- Permission to call /g2x reload'
    - 'g2x.reset    <-- Permission to call /g2x reset'
    - 'g2x.disable  <-- Permission to call /g2x disable'
    - 'g2x.update   <-- Permission to see update message ingame'
    - 'g2x.use      <-- Permission to use the rightclick feature'
