 name: Gold2Xp
 version: 1.0
 description: Requested Plugin
 author: DieFriiks
 authors: [undeaD_D] 
 website: http://www.pokemon-online.xyz/
 
 main: xyz.diefriiks.gold2xp.Gold2xp
 database: false
 
 commands:
   g2x:
     description: Gold2XP Admin Command
     usage: /g2x <reset/reload/disable>
